using Microsoft.EntityFrameworkCore;

namespace DANGCAPNE.Data
{
    public static class SchemaPatchRunner
    {
        public static async Task EnsureDemoAccountsAsync(ApplicationDbContext db)
        {
            await EnsureDedicatedItAndManagerAccountsAsync(db);
            await EnsureAccountingTeamAsync(db);
            await RemoveEmailApprovalFlowAsync(db);
        }

        private static async Task RemoveEmailApprovalFlowAsync(ApplicationDbContext db)
        {
            // Convert legacy email-approval pending accounts to active, and ensure they have an employee code.
            var now = DateTime.UtcNow;
            var pendingUsers = await db.Users
                .Where(u => u.Status == "PendingApproval")
                .ToListAsync();

            if (!pendingUsers.Any())
            {
                return;
            }

            foreach (var user in pendingUsers)
            {
                user.Status = "Active";
                user.UpdatedAt = now;
            }

            await db.SaveChangesAsync();

            foreach (var user in pendingUsers.Where(u => string.IsNullOrWhiteSpace(u.EmployeeCode) || u.EmployeeCode == "PENDING" || u.EmployeeCode == "TEMP"))
            {
                user.EmployeeCode = $"EMP{user.Id:D4}";
                user.UpdatedAt = now;
            }

            await db.SaveChangesAsync();
        }

        public static async Task EnsureExtendedSchemaAsync(ApplicationDbContext db)
        {
            var commands = new[]
            {
                """
                CREATE TABLE IF NOT EXISTS "AuthAuditLogs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NULL,
                    "Email" character varying(256) NULL,
                    "Action" character varying(50) NOT NULL,
                    "IsSuccess" boolean NOT NULL DEFAULT FALSE,
                    "Details" character varying(1000) NULL,
                    "IpAddress" character varying(50) NULL,
                    "UserAgent" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_AuthAuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_AuthAuditLogs_UserId_CreatedAt" ON "AuthAuditLogs" ("UserId", "CreatedAt");
                """,
                """
                CREATE TABLE IF NOT EXISTS "PasswordHistories" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "PasswordHash" character varying(500) NOT NULL,
                    "ChangedByUserId" integer NULL,
                    "ChangeSource" character varying(50) NOT NULL DEFAULT 'SelfService',
                    "ChangedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_PasswordHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_PasswordHistories_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "WorkflowRoutingRules" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "WorkflowId" integer NOT NULL,
                    "StepId" integer NULL,
                    "RuleName" character varying(150) NOT NULL,
                    "RoutingType" character varying(30) NOT NULL,
                    "ConditionExpression" character varying(2000) NULL,
                    "Priority" integer NOT NULL DEFAULT 0,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_WorkflowRoutingRules_Workflows_WorkflowId" FOREIGN KEY ("WorkflowId") REFERENCES "Workflows" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_WorkflowRoutingRules_WorkflowSteps_StepId" FOREIGN KEY ("StepId") REFERENCES "WorkflowSteps" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "SalaryAdvanceRequests" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "SourceRequestId" integer NULL,
                    "UserId" integer NOT NULL,
                    "Amount" numeric(18,2) NOT NULL DEFAULT 0,
                    "Reason" character varying(500) NOT NULL,
                    "NeededByDate" timestamp without time zone NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "ApprovedByUserId" integer NULL,
                    "ApprovedAt" timestamp without time zone NULL,
                    "PayrollMonth" character varying(20) NOT NULL,
                    "Notes" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_SalaryAdvanceRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_SalaryAdvanceRequests_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalaryAdvanceRequests_SourceRequestId" ON "SalaryAdvanceRequests" ("SourceRequestId");
                """,
                """
                CREATE TABLE IF NOT EXISTS "InsuranceImportBatches" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "FileName" character varying(255) NOT NULL,
                    "ImportedByUserId" integer NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "TotalRows" integer NOT NULL DEFAULT 0,
                    "SuccessRows" integer NOT NULL DEFAULT 0,
                    "FailedRows" integer NOT NULL DEFAULT 0,
                    "Summary" character varying(2000) NULL,
                    "ImportedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_InsuranceImportBatches_Users_ImportedByUserId" FOREIGN KEY ("ImportedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "PayrollClosures" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "PayrollMonth" character varying(20) NOT NULL,
                    "ClosedByUserId" integer NOT NULL,
                    "ClosedAt" timestamp without time zone NOT NULL,
                    "EmployeeCount" integer NOT NULL DEFAULT 0,
                    "TimesheetCount" integer NOT NULL DEFAULT 0,
                    "TotalWorkHours" numeric(18,2) NOT NULL DEFAULT 0,
                    "TotalOtHours" numeric(18,2) NOT NULL DEFAULT 0,
                    "PendingAdvanceCount" integer NOT NULL DEFAULT 0,
                    "Notes" character varying(1000) NULL,
                    CONSTRAINT "FK_PayrollClosures_Users_ClosedByUserId" FOREIGN KEY ("ClosedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PayrollClosures_TenantId_PayrollMonth" ON "PayrollClosures" ("TenantId", "PayrollMonth");
                """,
                """
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "BaseSalary" numeric(18,2) NOT NULL DEFAULT 0;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "SalaryCoefficient" numeric(18,2) NOT NULL DEFAULT 1;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "StandardWorkDays" integer NOT NULL DEFAULT 26;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "StandardWorkHoursPerDay" numeric(18,2) NOT NULL DEFAULT 8;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "OvertimeHourlyMultiplier" numeric(18,2) NOT NULL DEFAULT 1.5;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LatePenaltyPerMinute" numeric(18,2) NOT NULL DEFAULT 2000;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FixedAllowance" numeric(18,2) NOT NULL DEFAULT 0;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "OtherIncome" numeric(18,2) NOT NULL DEFAULT 0;
                UPDATE "Users"
                SET "BaseSalary" = CASE
                    WHEN "DepartmentId" = 1 OR "JobTitleId" = 1 OR "PositionId" = 1 THEN 80000000
                    WHEN "DepartmentId" = 4 OR "PositionId" = 4 THEN 17000000
                    WHEN "DepartmentId" = 3 THEN 15000000
                    WHEN "JobTitleId" = 3 OR "PositionId" IN (2, 3, 5) THEN 25000000
                    ELSE 10000000
                END
                WHERE COALESCE("BaseSalary", 0) <= 0;
                """,
                """
                CREATE TABLE IF NOT EXISTS "PayrollSlips" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "PayrollClosureId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "PayrollMonth" character varying(20) NOT NULL,
                    "BaseSalary" numeric(18,2) NOT NULL DEFAULT 0,
                    "SalaryCoefficient" numeric(18,2) NOT NULL DEFAULT 1,
                    "StandardWorkDays" integer NOT NULL DEFAULT 26,
                    "StandardWorkHoursPerDay" numeric(18,2) NOT NULL DEFAULT 8,
                    "ActualWorkingDays" integer NOT NULL DEFAULT 0,
                    "ActualWorkHours" numeric(18,2) NOT NULL DEFAULT 0,
                    "OvertimeHours" numeric(18,2) NOT NULL DEFAULT 0,
                    "LateMinutes" integer NOT NULL DEFAULT 0,
                    "HourlyRate" numeric(18,2) NOT NULL DEFAULT 0,
                    "MainSalary" numeric(18,2) NOT NULL DEFAULT 0,
                    "OvertimeSalary" numeric(18,2) NOT NULL DEFAULT 0,
                    "FixedAllowance" numeric(18,2) NOT NULL DEFAULT 0,
                    "OtherIncome" numeric(18,2) NOT NULL DEFAULT 0,
                    "LatePenalty" numeric(18,2) NOT NULL DEFAULT 0,
                    "AdvanceDeduction" numeric(18,2) NOT NULL DEFAULT 0,
                    "NetSalary" numeric(18,2) NOT NULL DEFAULT 0,
                    "PdfPath" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_PayrollSlips_PayrollClosures_PayrollClosureId" FOREIGN KEY ("PayrollClosureId") REFERENCES "PayrollClosures" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_PayrollSlips_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PayrollSlips_PayrollClosureId_UserId" ON "PayrollSlips" ("PayrollClosureId", "UserId");
                """,
                """
                UPDATE "SlaConfigs"
                SET "ReminderHours" = 4,
                    "EscalationHours" = 8
                WHERE "FormTemplateId" = 1;

                UPDATE "SlaConfigs"
                SET "ReminderHours" = 24,
                    "EscalationHours" = 36
                WHERE "FormTemplateId" = 4;
                """,
                """
                CREATE TABLE IF NOT EXISTS "AttendanceAdjustmentRequests" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "SourceRequestId" integer NULL,
                    "UserId" integer NOT NULL,
                    "TimesheetId" integer NULL,
                    "AttendanceDate" timestamp without time zone NOT NULL,
                    "RequestedCheckIn" timestamp without time zone NULL,
                    "RequestedCheckOut" timestamp without time zone NULL,
                    "Reason" character varying(500) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "ApprovedByUserId" integer NULL,
                    "ProcessedAt" timestamp without time zone NULL,
                    "Notes" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_AttendanceAdjustmentRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AttendanceAdjustmentRequests_Timesheets_TimesheetId" FOREIGN KEY ("TimesheetId") REFERENCES "Timesheets" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AttendanceAdjustmentRequests_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_AttendanceAdjustmentRequests_UserId_AttendanceDate" ON "AttendanceAdjustmentRequests" ("UserId", "AttendanceDate");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_AttendanceAdjustmentRequests_SourceRequestId" ON "AttendanceAdjustmentRequests" ("SourceRequestId");
                """,
                """
                CREATE TABLE IF NOT EXISTS "LateEarlyRequests" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "SourceRequestId" integer NULL,
                    "UserId" integer NOT NULL,
                    "AttendanceDate" timestamp without time zone NOT NULL,
                    "RequestType" character varying(30) NOT NULL,
                    "ExpectedTime" timestamp without time zone NOT NULL,
                    "ActualTime" timestamp without time zone NOT NULL,
                    "Reason" character varying(500) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "ApprovedByUserId" integer NULL,
                    "ProcessedAt" timestamp without time zone NULL,
                    "Notes" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_LateEarlyRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_LateEarlyRequests_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_LateEarlyRequests_UserId_AttendanceDate" ON "LateEarlyRequests" ("UserId", "AttendanceDate");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_LateEarlyRequests_SourceRequestId" ON "LateEarlyRequests" ("SourceRequestId");
                """,
                """
                CREATE TABLE IF NOT EXISTS "ShiftImportBatches" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "FileName" character varying(255) NOT NULL,
                    "ImportedByUserId" integer NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "TotalRows" integer NOT NULL DEFAULT 0,
                    "SuccessRows" integer NOT NULL DEFAULT 0,
                    "FailedRows" integer NOT NULL DEFAULT 0,
                    "Summary" character varying(2000) NULL,
                    "ImportedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_ShiftImportBatches_Users_ImportedByUserId" FOREIGN KEY ("ImportedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "AutoShiftPlans" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "Name" character varying(150) NOT NULL,
                    "FromDate" timestamp without time zone NOT NULL,
                    "ToDate" timestamp without time zone NOT NULL,
                    "DepartmentId" integer NULL,
                    "Strategy" character varying(30) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "GeneratedByUserId" integer NOT NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_AutoShiftPlans_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AutoShiftPlans_Users_GeneratedByUserId" FOREIGN KEY ("GeneratedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "AutoShiftPlanItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "PlanId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "ShiftId" integer NOT NULL,
                    "WorkDate" timestamp without time zone NOT NULL,
                    "ConfidenceScore" double precision NOT NULL DEFAULT 0,
                    "Source" character varying(30) NOT NULL,
                    CONSTRAINT "FK_AutoShiftPlanItems_AutoShiftPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "AutoShiftPlans" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_AutoShiftPlanItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AutoShiftPlanItems_Shifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "Shifts" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_AutoShiftPlanItems_UserId_WorkDate" ON "AutoShiftPlanItems" ("UserId", "WorkDate");
                """,
                """
                CREATE TABLE IF NOT EXISTS "ShiftTaskAssignments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "ShiftId" integer NOT NULL,
                    "WorkDate" timestamp without time zone NOT NULL,
                    "AssignedToUserId" integer NOT NULL,
                    "AssignedByUserId" integer NOT NULL,
                    "Title" character varying(200) NOT NULL,
                    "Description" character varying(2000) NULL,
                    "Priority" character varying(20) NOT NULL,
                    "Status" character varying(20) NOT NULL,
                    "DueAt" timestamp without time zone NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_ShiftTaskAssignments_Shifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "Shifts" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_ShiftTaskAssignments_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_ShiftTaskAssignments_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "EmployeeOnlineSessions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "SessionToken" character varying(100) NOT NULL,
                    "LoginAt" timestamp without time zone NOT NULL,
                    "LastSeenAt" timestamp without time zone NOT NULL,
                    "LogoutAt" timestamp without time zone NULL,
                    "Status" character varying(20) NOT NULL,
                    "LastIpAddress" character varying(50) NULL,
                    "DeviceName" character varying(255) NULL,
                    CONSTRAINT "FK_EmployeeOnlineSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_EmployeeOnlineSessions_UserId_Status" ON "EmployeeOnlineSessions" ("UserId", "Status");
                """,
                """
                CREATE TABLE IF NOT EXISTS "DigitalSignatureProfiles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "ProviderName" character varying(100) NOT NULL,
                    "CertificateThumbprint" character varying(200) NULL,
                    "SignatureImageUrl" character varying(500) NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_DigitalSignatureProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "KpiSnapshots" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NULL,
                    "DepartmentId" integer NULL,
                    "SnapshotDate" timestamp without time zone NOT NULL,
                    "MetricName" character varying(100) NOT NULL,
                    "MetricValue" double precision NOT NULL DEFAULT 0,
                    "Unit" character varying(20) NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_KpiSnapshots_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_KpiSnapshots_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "RequestCategoryReportSnapshots" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "Category" character varying(100) NOT NULL,
                    "FromDate" timestamp without time zone NOT NULL,
                    "ToDate" timestamp without time zone NOT NULL,
                    "TotalRequests" integer NOT NULL DEFAULT 0,
                    "ApprovedRequests" integer NOT NULL DEFAULT 0,
                    "RejectedRequests" integer NOT NULL DEFAULT 0,
                    "PendingRequests" integer NOT NULL DEFAULT 0,
                    "AverageHoursToComplete" double precision NOT NULL DEFAULT 0,
                    "GeneratedByUserId" integer NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_RequestCategoryReportSnapshots_Users_GeneratedByUserId" FOREIGN KEY ("GeneratedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "CashTransactions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "TransactionType" character varying(20) NOT NULL,
                    "Channel" character varying(20) NOT NULL,
                    "TransactionDate" timestamp without time zone NOT NULL,
                    "Amount" numeric(18,2) NOT NULL DEFAULT 0,
                    "Content" character varying(200) NOT NULL DEFAULT '',
                    "CounterpartyName" character varying(200) NOT NULL DEFAULT '',
                    "CounterpartyType" character varying(50) NOT NULL DEFAULT 'Other',
                    "ReferenceCode" character varying(100) NULL,
                    "AttachmentPath" character varying(500) NULL,
                    "Status" character varying(30) NOT NULL DEFAULT 'Pending',
                    "CreatedByUserId" integer NOT NULL,
                    "ApprovedByUserId" integer NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_CashTransactions_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_CashTransactions_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_CashTransactions_TenantId_TransactionDate" ON "CashTransactions" ("TenantId", "TransactionDate");
                """,
                """
                CREATE TABLE IF NOT EXISTS "InvoiceRecords" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "InvoiceType" character varying(30) NOT NULL,
                    "InvoiceNo" character varying(50) NOT NULL,
                    "CounterpartyName" character varying(200) NOT NULL DEFAULT '',
                    "TaxCode" character varying(50) NOT NULL DEFAULT '',
                    "InvoiceDate" timestamp without time zone NOT NULL,
                    "DueDate" timestamp without time zone NOT NULL,
                    "Amount" numeric(18,2) NOT NULL DEFAULT 0,
                    "PaidAmount" numeric(18,2) NOT NULL DEFAULT 0,
                    "CreditLimit" numeric(18,2) NOT NULL DEFAULT 0,
                    "Status" character varying(30) NOT NULL DEFAULT 'Open',
                    "Notes" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_InvoiceRecords_TenantId_DueDate" ON "InvoiceRecords" ("TenantId", "DueDate");
                """,
                """
                CREATE TABLE IF NOT EXISTS "AccountingDocuments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "DocumentType" character varying(30) NOT NULL,
                    "DocumentNo" character varying(100) NOT NULL,
                    "VendorName" character varying(200) NOT NULL DEFAULT '',
                    "TaxCode" character varying(50) NOT NULL DEFAULT '',
                    "DocumentDate" timestamp without time zone NOT NULL,
                    "Amount" numeric(18,2) NOT NULL DEFAULT 0,
                    "PdfPath" character varying(500) NULL,
                    "XmlPath" character varying(500) NULL,
                    "UploadedByUserId" integer NOT NULL,
                    "UploadedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_AccountingDocuments_Users_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_AccountingDocuments_TenantId_DocumentDate" ON "AccountingDocuments" ("TenantId", "DocumentDate");
                """
            };

            var combinedCommands = string.Join("\n\n", commands);
            await db.Database.ExecuteSqlRawAsync(combinedCommands);

            var alterCommands = new[]
            {
                """
                ALTER TABLE "PasswordHistories" ADD COLUMN IF NOT EXISTS "TenantId" integer NOT NULL DEFAULT 1;
                ALTER TABLE "PasswordHistories" ADD COLUMN IF NOT EXISTS "ChangeSource" character varying(50) NOT NULL DEFAULT 'SelfService';
                """,
                """
                ALTER TABLE "WorkflowRoutingRules" ADD COLUMN IF NOT EXISTS "RouteType" character varying(20) NOT NULL DEFAULT 'Sequential';
                ALTER TABLE "WorkflowRoutingRules" ADD COLUMN IF NOT EXISTS "ParallelGroupCode" character varying(50) NULL;
                ALTER TABLE "WorkflowRoutingRules" ADD COLUMN IF NOT EXISTS "MinApprovalsRequired" integer NOT NULL DEFAULT 1;
                UPDATE "WorkflowRoutingRules"
                SET "RouteType" = 'Sequential'
                WHERE "RouteType" IS NULL OR "RouteType" = '';
                """,
                """
                ALTER TABLE "DigitalSignatureProfiles" ADD COLUMN IF NOT EXISTS "SignatureName" character varying(150) NOT NULL DEFAULT 'Chá»¯ kÃ½ máº·c Ä‘á»‹nh';
                """,
                """
                ALTER TABLE "KpiSnapshots" ADD COLUMN IF NOT EXISTS "MetricCode" character varying(50) NOT NULL DEFAULT 'GENERAL';
                ALTER TABLE "KpiSnapshots" ADD COLUMN IF NOT EXISTS "Category" character varying(50) NOT NULL DEFAULT 'General';
                """,
                """
                ALTER TABLE "RequestCategoryReportSnapshots" ADD COLUMN IF NOT EXISTS "SnapshotDate" timestamp without time zone NOT NULL DEFAULT NOW();
                """,
                """
                ALTER TABLE "AuthAuditLogs" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp without time zone NOT NULL DEFAULT NOW();
                """,
                """
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "RegisteredMacAddress" character varying(32) NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "RegisteredLoginIp" character varying(64) NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "RememberMeTokenHash" character varying(128) NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "RememberMeExpiresAt" timestamp without time zone NULL;
                UPDATE "Users"
                SET "EmployeeCode" = CASE
                    WHEN "Email" = 'admin@company.com' THEN 'AD001'
                    WHEN "Email" = 'hr@company.com' THEN 'HR001'
                    WHEN "Email" = 'itmanager@company.com' THEN 'ITM001'
                    WHEN "Email" = 'manager@company.com' THEN 'MNG001'
                    WHEN "Email" = 'employee@company.com' THEN 'NV001'
                    WHEN "Email" = 'accountant@company.com' THEN 'KT001'
                    WHEN "Email" = 'dev@company.com' THEN 'NV002'
                    WHEN "Email" = 'sales@company.com' THEN 'NV003'
                    WHEN "Email" = 'marketing@company.com' THEN 'NV004'
                    ELSE "EmployeeCode"
                END;
                INSERT INTO "Departments" ("TenantId", "Name", "Code", "IsActive", "CreatedAt")
                SELECT 1, 'PhÃ²ng CÃ´ng nghá»‡ ThÃ´ng tin', 'IT', TRUE, NOW()
                WHERE NOT EXISTS (
                    SELECT 1 FROM "Departments" WHERE "TenantId" = 1 AND "Code" = 'IT'
                );

                INSERT INTO "Roles" ("TenantId", "Name", "Description", "CreatedAt")
                SELECT 1, 'IT', 'Váº­n hÃ nh ká»¹ thuáº­t, cáº¥p mÃ£ nhÃ¢n viÃªn vÃ  há»— trá»£ truy cáº­p', NOW()
                WHERE NOT EXISTS (
                    SELECT 1 FROM "Roles" WHERE "TenantId" = 1 AND "Name" = 'IT'
                );

                INSERT INTO "Roles" ("TenantId", "Name", "Description", "CreatedAt")
                SELECT 1, 'ITManager', 'Quáº£n lÃ½ phÃ²ng IT, tÃ¡ch biá»‡t vá»›i Manager chung', NOW()
                WHERE NOT EXISTS (
                    SELECT 1 FROM "Roles" WHERE "TenantId" = 1 AND "Name" = 'ITManager'
                );

                INSERT INTO "Permissions" ("TenantId", "Name", "Code", "Description", "IsActive", "CreatedAt")
                SELECT 1, 'Issue Employee Code', 'EMPLOYEE_CODE_ISSUE', 'Issue employee code by department', TRUE, NOW()
                WHERE NOT EXISTS (
                    SELECT 1 FROM "Permissions" WHERE "TenantId" = 1 AND "Code" = 'EMPLOYEE_CODE_ISSUE'
                );

                INSERT INTO "Permissions" ("TenantId", "Name", "Code", "Description", "IsActive", "CreatedAt")
                SELECT 1, 'Support Account Access', 'ACCOUNT_SUPPORT', 'Reset login IP, password and access states', TRUE, NOW()
                WHERE NOT EXISTS (
                    SELECT 1 FROM "Permissions" WHERE "TenantId" = 1 AND "Code" = 'ACCOUNT_SUPPORT'
                );

                INSERT INTO "Permissions" ("TenantId", "Name", "Code", "Description", "IsActive", "CreatedAt")
                SELECT 1, 'Reset Trusted Device', 'DEVICE_RESET', 'Clear trusted device and biometric bindings', TRUE, NOW()
                WHERE NOT EXISTS (
                    SELECT 1 FROM "Permissions" WHERE "TenantId" = 1 AND "Code" = 'DEVICE_RESET'
                );

                INSERT INTO "RolePermissions" ("RoleId", "PermissionId", "AssignedAt")
                SELECT r."Id", p."Id", NOW()
                FROM "Roles" r
                INNER JOIN "Permissions" p ON p."TenantId" = r."TenantId"
                WHERE r."TenantId" = 1
                  AND r."Name" = 'IT'
                  AND p."Code" = 'EMPLOYEE_CODE_ISSUE'
                  AND NOT EXISTS (
                      SELECT 1 FROM "RolePermissions" rp
                      WHERE rp."RoleId" = r."Id" AND rp."PermissionId" = p."Id"
                  );

                INSERT INTO "RolePermissions" ("RoleId", "PermissionId", "AssignedAt")
                SELECT r."Id", p."Id", NOW()
                FROM "Roles" r
                INNER JOIN "Permissions" p ON p."TenantId" = r."TenantId"
                WHERE r."TenantId" = 1
                  AND r."Name" = 'IT'
                  AND p."Code" = 'ACCOUNT_SUPPORT'
                  AND NOT EXISTS (
                      SELECT 1 FROM "RolePermissions" rp
                      WHERE rp."RoleId" = r."Id" AND rp."PermissionId" = p."Id"
                  );

                INSERT INTO "RolePermissions" ("RoleId", "PermissionId", "AssignedAt")
                SELECT r."Id", p."Id", NOW()
                FROM "Roles" r
                INNER JOIN "Permissions" p ON p."TenantId" = r."TenantId"
                WHERE r."TenantId" = 1
                  AND r."Name" = 'IT'
                  AND p."Code" = 'DEVICE_RESET'
                  AND NOT EXISTS (
                      SELECT 1 FROM "RolePermissions" rp
                      WHERE rp."RoleId" = r."Id" AND rp."PermissionId" = p."Id"
                  );

                INSERT INTO "RolePermissions" ("RoleId", "PermissionId", "AssignedAt")
                SELECT r."Id", p."Id", NOW()
                FROM "Roles" r
                INNER JOIN "Permissions" p ON p."TenantId" = r."TenantId"
                WHERE r."TenantId" = 1
                  AND r."Name" = 'Admin'
                  AND p."Code" IN ('EMPLOYEE_CODE_ISSUE', 'ACCOUNT_SUPPORT', 'DEVICE_RESET')
                  AND NOT EXISTS (
                      SELECT 1 FROM "RolePermissions" rp
                      WHERE rp."RoleId" = r."Id" AND rp."PermissionId" = p."Id"
                  );

                INSERT INTO "UserRoles" ("UserId", "RoleId", "AssignedAt")
                SELECT u."Id", r."Id", NOW()
                FROM "Users" u
                CROSS JOIN "Roles" r
                WHERE lower(u."Email") = 'dev@company.com'
                  AND r."TenantId" = u."TenantId"
                  AND r."Name" = 'IT'
                  AND NOT EXISTS (
                      SELECT 1 FROM "UserRoles" ur
                      WHERE ur."UserId" = u."Id" AND ur."RoleId" = r."Id"
                  );
                """,
                """
                CREATE TABLE IF NOT EXISTS "AllowedIps" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL DEFAULT 1,
                    "IpAddress" character varying(64) NOT NULL,
                    "Label" character varying(200) NOT NULL DEFAULT '',
                    "AddedByUserId" integer NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp without time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAt" timestamp without time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "FK_AllowedIps_Users_AddedByUserId" FOREIGN KEY ("AddedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_AllowedIps_TenantId_IsActive" ON "AllowedIps" ("TenantId", "IsActive");
                CREATE INDEX IF NOT EXISTS "IX_AllowedIps_TenantId_IpAddress" ON "AllowedIps" ("TenantId", "IpAddress");
                """,
                """
                INSERT INTO "CashTransactions" ("TenantId", "TransactionType", "Channel", "TransactionDate", "Amount", "Content", "CounterpartyName", "CounterpartyType", "ReferenceCode", "Status", "CreatedByUserId", "ApprovedByUserId", "CreatedAt", "UpdatedAt")
                SELECT 1, 'Income', 'Bank', NOW() - INTERVAL '3 day', 85000000, 'Thu tien thanh toan hop dong thang 4', 'Cong ty Minh Phat', 'Customer', 'PT-2026-001', 'Approved', 6, 6, NOW(), NOW()
                WHERE NOT EXISTS (SELECT 1 FROM "CashTransactions" WHERE "ReferenceCode" = 'PT-2026-001');

                INSERT INTO "CashTransactions" ("TenantId", "TransactionType", "Channel", "TransactionDate", "Amount", "Content", "CounterpartyName", "CounterpartyType", "ReferenceCode", "Status", "CreatedByUserId", "ApprovedByUserId", "CreatedAt", "UpdatedAt")
                SELECT 1, 'Expense', 'Cash', NOW() - INTERVAL '2 day', 12500000, 'Chi mua van phong pham va chi tiep khach', 'Nha sach Van Phong Xanh', 'Vendor', 'PC-2026-011', 'Approved', 6, 6, NOW(), NOW()
                WHERE NOT EXISTS (SELECT 1 FROM "CashTransactions" WHERE "ReferenceCode" = 'PC-2026-011');

                INSERT INTO "CashTransactions" ("TenantId", "TransactionType", "Channel", "TransactionDate", "Amount", "Content", "CounterpartyName", "CounterpartyType", "ReferenceCode", "Status", "CreatedByUserId", "CreatedAt", "UpdatedAt")
                SELECT 1, 'Expense', 'Bank', NOW(), 18000000, 'De nghi thanh toan chi phi dich vu marketing', 'Blue Media Agency', 'Vendor', 'UNC-2026-005', 'Pending', 6, NOW(), NOW()
                WHERE NOT EXISTS (SELECT 1 FROM "CashTransactions" WHERE "ReferenceCode" = 'UNC-2026-005');

                INSERT INTO "InvoiceRecords" ("TenantId", "InvoiceType", "InvoiceNo", "CounterpartyName", "TaxCode", "InvoiceDate", "DueDate", "Amount", "PaidAmount", "CreditLimit", "Status", "Notes", "CreatedAt")
                SELECT 1, 'Receivable', 'AR-2026-0008', 'Cong ty Minh Phat', '0312345678', NOW() - INTERVAL '10 day', NOW() + INTERVAL '3 day', 120000000, 30000000, 100000000, 'Partial', 'Cong no khach hang can nhac thu', NOW()
                WHERE NOT EXISTS (SELECT 1 FROM "InvoiceRecords" WHERE "InvoiceNo" = 'AR-2026-0008');

                INSERT INTO "InvoiceRecords" ("TenantId", "InvoiceType", "InvoiceNo", "CounterpartyName", "TaxCode", "InvoiceDate", "DueDate", "Amount", "PaidAmount", "CreditLimit", "Status", "Notes", "CreatedAt")
                SELECT 1, 'Payable', 'AP-2026-0015', 'Blue Media Agency', '0309988776', NOW() - INTERVAL '7 day', NOW() + INTERVAL '2 day', 45000000, 0, 0, 'Open', 'Can thanh toan trong tuan nay', NOW()
                WHERE NOT EXISTS (SELECT 1 FROM "InvoiceRecords" WHERE "InvoiceNo" = 'AP-2026-0015');

                INSERT INTO "InvoiceRecords" ("TenantId", "InvoiceType", "InvoiceNo", "CounterpartyName", "TaxCode", "InvoiceDate", "DueDate", "Amount", "PaidAmount", "CreditLimit", "Status", "Notes", "CreatedAt")
                SELECT 1, 'Receivable', 'AR-2026-0010', 'Cong ty Gia Bao', '0318888666', NOW() - INTERVAL '20 day', NOW() + INTERVAL '5 day', 65000000, 0, 70000000, 'Open', 'Can doi chieu hop dong truoc khi thu', NOW()
                WHERE NOT EXISTS (SELECT 1 FROM "InvoiceRecords" WHERE "InvoiceNo" = 'AR-2026-0010');

                INSERT INTO "AccountingDocuments" ("TenantId", "DocumentType", "DocumentNo", "VendorName", "TaxCode", "DocumentDate", "Amount", "PdfPath", "XmlPath", "UploadedByUserId", "UploadedAt")
                SELECT 1, 'InvoiceIn', 'INV-IN-2026-045', 'Blue Media Agency', '0309988776', NOW() - INTERVAL '7 day', 45000000, '/samples/docs/invoice-in-2026-045.pdf', '/samples/docs/invoice-in-2026-045.xml', 6, NOW()
                WHERE NOT EXISTS (SELECT 1 FROM "AccountingDocuments" WHERE "DocumentNo" = 'INV-IN-2026-045');

                INSERT INTO "AccountingDocuments" ("TenantId", "DocumentType", "DocumentNo", "VendorName", "TaxCode", "DocumentDate", "Amount", "PdfPath", "XmlPath", "UploadedByUserId", "UploadedAt")
                SELECT 1, 'InvoiceOut', 'INV-OUT-2026-018', 'Cong ty Minh Phat', '0312345678', NOW() - INTERVAL '5 day', 85000000, '/samples/docs/invoice-out-2026-018.pdf', '/samples/docs/invoice-out-2026-018.xml', 6, NOW()
                WHERE NOT EXISTS (SELECT 1 FROM "AccountingDocuments" WHERE "DocumentNo" = 'INV-OUT-2026-018');
                """
            };

            var combinedAlterCommands = string.Join("\n\n", alterCommands);
            await db.Database.ExecuteSqlRawAsync(combinedAlterCommands);

            await EnsureDemoAccountsAsync(db);
        }

        private static async Task EnsureAccountingTeamAsync(ApplicationDbContext db)
        {
            const int tenantId = 1;
            var now = DateTime.UtcNow;
            var defaultPasswordHash = HashSeedPassword("Admin@123");

            var accountingDept = await db.Departments.FirstOrDefaultAsync(d => d.TenantId == tenantId && (d.Code == "ACC" || d.Name == "Phòng Kế toán"));
            if (accountingDept == null)
            {
                accountingDept = new Models.Organization.Department { TenantId = tenantId, Name = "Phòng Kế toán", Code = "ACC", IsActive = true, CreatedAt = now };
                db.Departments.Add(accountingDept);
                await db.SaveChangesAsync();
            }

            var defaultBranch = await db.Branches.Where(b => b.TenantId == tenantId).OrderBy(b => b.Id).FirstOrDefaultAsync();

            var chiefPosition = await db.Positions.FirstOrDefaultAsync(p => p.TenantId == tenantId && p.Name == "Kế toán trưởng");
            if (chiefPosition == null)
            {
                chiefPosition = new Models.Organization.Position { TenantId = tenantId, Name = "Kế toán trưởng", DepartmentId = accountingDept.Id };
                db.Positions.Add(chiefPosition);
                await db.SaveChangesAsync();
            }

            var staffPosition = await db.Positions.FirstOrDefaultAsync(p => p.TenantId == tenantId && p.Name == "Nhân viên kế toán");
            if (staffPosition == null)
            {
                staffPosition = new Models.Organization.Position { TenantId = tenantId, Name = "Nhân viên kế toán", DepartmentId = accountingDept.Id };
                db.Positions.Add(staffPosition);
                await db.SaveChangesAsync();
            }

            var chiefRoleId = await EnsureRoleAsync(db, tenantId, "ChiefAccountant", "Kế toán trưởng - toàn quyền phân hệ kế toán");
            var staffRoleId = await EnsureRoleAsync(db, tenantId, "AccountantStaff", "Nhân viên kế toán - nhập phiếu thu chi và theo dõi công nợ");
            var accountantRoleId = await EnsureRoleAsync(db, tenantId, "Accountant", "Phân hệ kế toán");

            // Kế toán trưởng: dùng user sẵn có accountant@company.com
            var chiefUser = await db.Users.FirstOrDefaultAsync(u => u.TenantId == tenantId && u.Email == "accountant@company.com");
            if (chiefUser == null)
            {
                chiefUser = new Models.Organization.User
                {
                    TenantId = tenantId,
                    FullName = "Vũ Thị Kế Toán Trưởng",
                    Email = "accountant@company.com",
                    PasswordHash = defaultPasswordHash,
                    EmployeeCode = "KT001",
                    DepartmentId = accountingDept.Id,
                    BranchId = defaultBranch?.Id ?? 1,
                    PositionId = chiefPosition.Id,
                    Phone = "0901234572",
                    Status = "Active",
                    CreatedAt = now,
                    UpdatedAt = now
                };
                db.Users.Add(chiefUser);
                await db.SaveChangesAsync();
            }
            else
            {
                chiefUser.FullName = "Vũ Thị Kế Toán Trưởng";
                chiefUser.EmployeeCode = "KT001";
                chiefUser.DepartmentId = accountingDept.Id;
                chiefUser.PositionId = chiefPosition.Id;
                chiefUser.Status = "Active";
                chiefUser.UpdatedAt = now;
                if (string.IsNullOrWhiteSpace(chiefUser.PasswordHash))
                {
                    chiefUser.PasswordHash = defaultPasswordHash;
                }
                await db.SaveChangesAsync();
            }

            await EnsureUserRoleAsync(db, chiefUser.Id, chiefRoleId);
            await EnsureUserRoleAsync(db, chiefUser.Id, accountantRoleId);

            // Nhân viên kế toán: tạo mới acctstaff@company.com / KT002
            var staffUser = await db.Users.FirstOrDefaultAsync(u => u.TenantId == tenantId && u.Email == "acctstaff@company.com");
            if (staffUser == null)
            {
                staffUser = new Models.Organization.User
                {
                    TenantId = tenantId,
                    FullName = "Trần Văn Nhân Viên Kế Toán",
                    Email = "acctstaff@company.com",
                    PasswordHash = defaultPasswordHash,
                    EmployeeCode = "KT002",
                    DepartmentId = accountingDept.Id,
                    BranchId = defaultBranch?.Id ?? 1,
                    PositionId = staffPosition.Id,
                    Phone = "0901234580",
                    Status = "Active",
                    CreatedAt = now,
                    UpdatedAt = now
                };
                db.Users.Add(staffUser);
                await db.SaveChangesAsync();
            }
            else
            {
                staffUser.FullName = "Trần Văn Nhân Viên Kế Toán";
                staffUser.EmployeeCode = "KT002";
                staffUser.DepartmentId = accountingDept.Id;
                staffUser.PositionId = staffPosition.Id;
                staffUser.Status = "Active";
                staffUser.UpdatedAt = now;
                if (string.IsNullOrWhiteSpace(staffUser.PasswordHash))
                {
                    staffUser.PasswordHash = defaultPasswordHash;
                }
                await db.SaveChangesAsync();
            }

            await EnsureUserRoleAsync(db, staffUser.Id, staffRoleId);
            await EnsureUserRoleAsync(db, staffUser.Id, accountantRoleId);

            // Nhân viên kế toán báo cáo cho Kế toán trưởng
            await UpsertPrimaryManagerAsync(db, staffUser.Id, chiefUser.Id);

            await db.SaveChangesAsync();
        }

        private static async Task EnsureDedicatedItAndManagerAccountsAsync(ApplicationDbContext db)
        {
            const int tenantId = 1;
            var now = DateTime.UtcNow;
            var defaultPasswordHash = HashSeedPassword("Admin@123");

            var itDepartment = await db.Departments.FirstOrDefaultAsync(d => d.TenantId == tenantId && d.Code == "IT");
            var salesDepartment = await db.Departments.FirstOrDefaultAsync(d => d.TenantId == tenantId && d.Code == "SALES");
            var headJobTitle = await db.JobTitles.FirstOrDefaultAsync(j => j.TenantId == tenantId && j.Name == "TrÆ°á»Ÿng phÃ²ng");
            var itManagerPosition = await db.Positions.FirstOrDefaultAsync(p => p.TenantId == tenantId && p.Name == "TrÆ°á»Ÿng phÃ²ng IT");
            var generalManagerPosition = await db.Positions.FirstOrDefaultAsync(p => p.TenantId == tenantId && p.Name == "TrÆ°á»Ÿng phÃ²ng KD");
            var defaultBranch = await db.Branches.Where(b => b.TenantId == tenantId).OrderBy(b => b.Id).FirstOrDefaultAsync();

            if (defaultBranch == null)
            {
                defaultBranch = new Models.Organization.Branch { TenantId = tenantId, Name = "Trá»¥ sá»Ÿ chÃ­nh", Address = "N/A", TimeZone = "SE Asia Standard Time" };
                db.Branches.Add(defaultBranch);
                await db.SaveChangesAsync();
            }

            if (salesDepartment == null)
            {
                salesDepartment = new Models.Organization.Department { TenantId = tenantId, Name = "PhÃ²ng Kinh doanh", Code = "SALES", IsActive = true, CreatedAt = now };
                db.Departments.Add(salesDepartment);
                await db.SaveChangesAsync();
            }

            if (itDepartment == null)
            {
                itDepartment = new Models.Organization.Department { TenantId = tenantId, Name = "PhÃ²ng CÃ´ng nghá»‡ ThÃ´ng tin", Code = "IT", IsActive = true, CreatedAt = now };
                db.Departments.Add(itDepartment);
                await db.SaveChangesAsync();
            }

            if (headJobTitle == null)
            {
                headJobTitle = new Models.Organization.JobTitle { TenantId = tenantId, Name = "TrÆ°á»Ÿng phÃ²ng", Level = 3 };
                db.JobTitles.Add(headJobTitle);
                await db.SaveChangesAsync();
            }

            if (itManagerPosition == null)
            {
                itManagerPosition = new Models.Organization.Position { TenantId = tenantId, Name = "TrÆ°á»Ÿng phÃ²ng IT", DepartmentId = itDepartment.Id };
                db.Positions.Add(itManagerPosition);
                await db.SaveChangesAsync();
            }

            if (generalManagerPosition == null)
            {
                generalManagerPosition = new Models.Organization.Position { TenantId = tenantId, Name = "TrÆ°á»Ÿng phÃ²ng KD", DepartmentId = salesDepartment.Id };
                db.Positions.Add(generalManagerPosition);
                await db.SaveChangesAsync();
            }

            var managerRoleId = await EnsureRoleAsync(db, tenantId, "Manager", "Quáº£n lÃ½");
            var itRoleId = await EnsureRoleAsync(db, tenantId, "IT", "Váº­n hÃ nh ká»¹ thuáº­t, cáº¥p mÃ£ nhÃ¢n viÃªn vÃ  há»— trá»£ truy cáº­p");
            var itManagerRoleId = await EnsureRoleAsync(db, tenantId, "ITManager", "Quáº£n lÃ½ phÃ²ng IT, tÃ¡ch biá»‡t vá»›i Manager chung");

            var employeeCodePermissionId = await EnsurePermissionAsync(db, tenantId, "Issue Employee Code", "EMPLOYEE_CODE_ISSUE", "Issue employee code by department");
            var accountSupportPermissionId = await EnsurePermissionAsync(db, tenantId, "Support Account Access", "ACCOUNT_SUPPORT", "Reset login IP, password and access states");
            var deviceResetPermissionId = await EnsurePermissionAsync(db, tenantId, "Reset Trusted Device", "DEVICE_RESET", "Clear trusted device and biometric bindings");

            await EnsureRolePermissionAsync(db, itRoleId, employeeCodePermissionId);
            await EnsureRolePermissionAsync(db, itRoleId, accountSupportPermissionId);
            await EnsureRolePermissionAsync(db, itRoleId, deviceResetPermissionId);
            await EnsureRolePermissionAsync(db, itManagerRoleId, employeeCodePermissionId);
            await EnsureRolePermissionAsync(db, itManagerRoleId, accountSupportPermissionId);
            await EnsureRolePermissionAsync(db, itManagerRoleId, deviceResetPermissionId);
            await EnsureRolePermissionAsync(db, 1, employeeCodePermissionId);
            await EnsureRolePermissionAsync(db, 1, accountSupportPermissionId);
            await EnsureRolePermissionAsync(db, 1, deviceResetPermissionId);

            var itManagerUser = await db.Users
                .FirstOrDefaultAsync(u => u.TenantId == tenantId &&
                    (u.Email == "itmanager@company.com" ||
                     (u.Email == "manager@company.com" && u.DepartmentId == itDepartment.Id && u.PositionId == itManagerPosition.Id) ||
                     (u.DepartmentId == itDepartment.Id && u.PositionId == itManagerPosition.Id)));

            if (itManagerUser == null)
            {
                itManagerUser = new Models.Organization.User
                {
                    TenantId = tenantId,
                    FullName = "Lê Văn IT Manager",
                    Email = "itmanager@company.com",
                    PasswordHash = defaultPasswordHash,
                    EmployeeCode = "ITM001",
                    DepartmentId = itDepartment.Id,
                    BranchId = defaultBranch.Id,
                    JobTitleId = headJobTitle.Id,
                    PositionId = itManagerPosition.Id,
                    Phone = "0901234569",
                    Status = "Active",
                    CreatedAt = now,
                    UpdatedAt = now
                };
                db.Users.Add(itManagerUser);
                await db.SaveChangesAsync();
            }
            else
            {
                itManagerUser.FullName = "Lê Văn IT Manager";
                itManagerUser.Email = "itmanager@company.com";
                itManagerUser.EmployeeCode = "ITM001";
                itManagerUser.DepartmentId = itDepartment.Id;
                itManagerUser.BranchId ??= defaultBranch.Id;
                itManagerUser.JobTitleId ??= headJobTitle.Id;
                itManagerUser.PositionId = itManagerPosition.Id;
                itManagerUser.Status = "Active";
                itManagerUser.UpdatedAt = now;
                if (string.IsNullOrWhiteSpace(itManagerUser.PasswordHash))
                {
                    itManagerUser.PasswordHash = defaultPasswordHash;
                }
                await db.SaveChangesAsync();
            }

            var generalManagerUser = await db.Users
                .FirstOrDefaultAsync(u => u.TenantId == tenantId && u.Email == "manager@company.com" && u.Id != itManagerUser.Id);

            if (generalManagerUser == null)
            {
                generalManagerUser = new Models.Organization.User
                {
                    TenantId = tenantId,
                    FullName = "Nguyễn Văn Manager",
                    Email = "manager@company.com",
                    PasswordHash = defaultPasswordHash,
                    EmployeeCode = "MNG001",
                    DepartmentId = salesDepartment.Id,
                    BranchId = defaultBranch.Id,
                    JobTitleId = headJobTitle.Id,
                    PositionId = generalManagerPosition.Id,
                    Phone = "0901234575",
                    Status = "Active",
                    CreatedAt = now,
                    UpdatedAt = now
                };
                db.Users.Add(generalManagerUser);
                await db.SaveChangesAsync();
            }
            else
            {
                generalManagerUser.FullName = "Nguyễn Văn Manager";
                generalManagerUser.EmployeeCode = "MNG001";
                generalManagerUser.DepartmentId = salesDepartment.Id;
                generalManagerUser.BranchId ??= defaultBranch.Id;
                generalManagerUser.JobTitleId ??= headJobTitle.Id;
                generalManagerUser.PositionId = generalManagerPosition.Id;
                generalManagerUser.Status = "Active";
                generalManagerUser.UpdatedAt = now;
                if (string.IsNullOrWhiteSpace(generalManagerUser.PasswordHash))
                {
                    generalManagerUser.PasswordHash = defaultPasswordHash;
                }
                await db.SaveChangesAsync();
            }

            // IT Manager is separate from Manager
            var mistakeRole = await db.UserRoles.FirstOrDefaultAsync(ur => ur.UserId == itManagerUser.Id && ur.RoleId == managerRoleId);
            if (mistakeRole != null) {
                db.UserRoles.Remove(mistakeRole);
                await db.SaveChangesAsync();
            }

            await EnsureUserRoleAsync(db, itManagerUser.Id, itManagerRoleId);
            await EnsureUserRoleAsync(db, generalManagerUser.Id, managerRoleId);

            var devUser = await db.Users.FirstOrDefaultAsync(u => u.TenantId == tenantId && u.Email == "dev@company.com");
            if (devUser != null)
            {
                await EnsureUserRoleAsync(db, devUser.Id, itRoleId);
            }

            await UpsertPrimaryManagerAsync(db, 4, itManagerUser.Id);
            await UpsertPrimaryManagerAsync(db, 5, itManagerUser.Id);
            await UpsertPrimaryManagerAsync(db, itManagerUser.Id, 1);
            await UpsertPrimaryManagerAsync(db, 7, generalManagerUser.Id);
            await UpsertPrimaryManagerAsync(db, generalManagerUser.Id, 1);

            await db.SaveChangesAsync();
        }

        private static async Task<int> EnsureRoleAsync(ApplicationDbContext db, int tenantId, string name, string description)
        {
            var role = await db.Roles.FirstOrDefaultAsync(r => r.TenantId == tenantId && r.Name == name);
            if (role == null)
            {
                role = new Models.Organization.Role
                {
                    TenantId = tenantId,
                    Name = name,
                    Description = description,
                    CreatedAt = DateTime.UtcNow
                };
                db.Roles.Add(role);
                await db.SaveChangesAsync();
            }
            else if (!string.Equals(role.Description, description, StringComparison.Ordinal))
            {
                role.Description = description;
                await db.SaveChangesAsync();
            }

            return role.Id;
        }

        private static async Task<int> EnsurePermissionAsync(ApplicationDbContext db, int tenantId, string name, string code, string description)
        {
            var permission = await db.Permissions.FirstOrDefaultAsync(p => p.TenantId == tenantId && p.Code == code);
            if (permission == null)
            {
                permission = new Models.Security.Permission
                {
                    TenantId = tenantId,
                    Name = name,
                    Code = code,
                    Description = description,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                db.Permissions.Add(permission);
                await db.SaveChangesAsync();
            }

            return permission.Id;
        }

        private static async Task EnsureRolePermissionAsync(ApplicationDbContext db, int roleId, int permissionId)
        {
            var exists = await db.RolePermissions.AnyAsync(rp => rp.RoleId == roleId && rp.PermissionId == permissionId);
            if (!exists)
            {
                db.RolePermissions.Add(new Models.Security.RolePermission
                {
                    RoleId = roleId,
                    PermissionId = permissionId,
                    AssignedAt = DateTime.UtcNow
                });
                await db.SaveChangesAsync();
            }
        }

        private static async Task EnsureUserRoleAsync(ApplicationDbContext db, int userId, int roleId)
        {
            var exists = await db.UserRoles.AnyAsync(ur => ur.UserId == userId && ur.RoleId == roleId);
            if (!exists)
            {
                db.UserRoles.Add(new Models.Organization.UserRole
                {
                    UserId = userId,
                    RoleId = roleId,
                    AssignedAt = DateTime.UtcNow
                });
                await db.SaveChangesAsync();
            }
        }

        private static async Task UpsertPrimaryManagerAsync(ApplicationDbContext db, int userId, int managerId)
        {
            var userExists = await db.Users.AnyAsync(u => u.Id == userId);
            var managerExists = await db.Users.AnyAsync(u => u.Id == managerId);
            if (!userExists || !managerExists) return;

            var relation = await db.UserManagers
                .Where(um => um.UserId == userId && um.IsPrimary)
                .OrderBy(um => um.Id)
                .FirstOrDefaultAsync();

            if (relation == null)
            {
                db.UserManagers.Add(new Models.Organization.UserManager
                {
                    UserId = userId,
                    ManagerId = managerId,
                    IsPrimary = true,
                    StartDate = DateTime.UtcNow
                });
            }
            else
            {
                relation.ManagerId = managerId;
                relation.IsPrimary = true;
                if (relation.StartDate == default)
                {
                    relation.StartDate = DateTime.UtcNow;
                }
            }
        }

        private static string HashSeedPassword(string password)
        {
            using var sha256 = System.Security.Cryptography.SHA256.Create();
            var bytes = sha256.ComputeHash(System.Text.Encoding.UTF8.GetBytes(password + "DANGCAPNE_SALT"));
            return Convert.ToBase64String(bytes);
        }
    }
}

