using Microsoft.EntityFrameworkCore;

namespace DANGCAPNE.Data
{
    public static class SchemaPatchRunner
    {
        public static async Task EnsureExtendedSchemaAsync(ApplicationDbContext db)
        {
            var commands = new[]
            {
                """
                CREATE TABLE IF NOT EXISTS "AuthAuditLogs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NULL,
                    "Email" character varying(256) NULL,
                    "Action" character varying(50) NOT NULL,
                    "IsSuccess" boolean NOT NULL DEFAULT FALSE,
                    "Details" character varying(1000) NULL,
                    "IpAddress" character varying(50) NULL,
                    "UserAgent" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_AuthAuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_AuthAuditLogs_UserId_CreatedAt" ON "AuthAuditLogs" ("UserId", "CreatedAt");
                """,
                """
                CREATE TABLE IF NOT EXISTS "PasswordHistories" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "PasswordHash" character varying(500) NOT NULL,
                    "ChangedByUserId" integer NULL,
                    "ChangeSource" character varying(50) NOT NULL DEFAULT 'SelfService',
                    "ChangedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_PasswordHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_PasswordHistories_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "WorkflowRoutingRules" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "WorkflowId" integer NOT NULL,
                    "StepId" integer NULL,
                    "RuleName" character varying(150) NOT NULL,
                    "RoutingType" character varying(30) NOT NULL,
                    "ConditionExpression" character varying(2000) NULL,
                    "Priority" integer NOT NULL DEFAULT 0,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_WorkflowRoutingRules_Workflows_WorkflowId" FOREIGN KEY ("WorkflowId") REFERENCES "Workflows" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_WorkflowRoutingRules_WorkflowSteps_StepId" FOREIGN KEY ("StepId") REFERENCES "WorkflowSteps" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "SalaryAdvanceRequests" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "SourceRequestId" integer NULL,
                    "UserId" integer NOT NULL,
                    "Amount" numeric(18,2) NOT NULL DEFAULT 0,
                    "Reason" character varying(500) NOT NULL,
                    "NeededByDate" timestamp without time zone NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "ApprovedByUserId" integer NULL,
                    "ApprovedAt" timestamp without time zone NULL,
                    "PayrollMonth" character varying(20) NOT NULL,
                    "Notes" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_SalaryAdvanceRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_SalaryAdvanceRequests_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalaryAdvanceRequests_SourceRequestId" ON "SalaryAdvanceRequests" ("SourceRequestId");
                """,
                """
                CREATE TABLE IF NOT EXISTS "InsuranceImportBatches" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "FileName" character varying(255) NOT NULL,
                    "ImportedByUserId" integer NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "TotalRows" integer NOT NULL DEFAULT 0,
                    "SuccessRows" integer NOT NULL DEFAULT 0,
                    "FailedRows" integer NOT NULL DEFAULT 0,
                    "Summary" character varying(2000) NULL,
                    "ImportedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_InsuranceImportBatches_Users_ImportedByUserId" FOREIGN KEY ("ImportedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "PayrollClosures" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "PayrollMonth" character varying(20) NOT NULL,
                    "ClosedByUserId" integer NOT NULL,
                    "ClosedAt" timestamp without time zone NOT NULL,
                    "EmployeeCount" integer NOT NULL DEFAULT 0,
                    "TimesheetCount" integer NOT NULL DEFAULT 0,
                    "TotalWorkHours" numeric(18,2) NOT NULL DEFAULT 0,
                    "TotalOtHours" numeric(18,2) NOT NULL DEFAULT 0,
                    "PendingAdvanceCount" integer NOT NULL DEFAULT 0,
                    "Notes" character varying(1000) NULL,
                    CONSTRAINT "FK_PayrollClosures_Users_ClosedByUserId" FOREIGN KEY ("ClosedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PayrollClosures_TenantId_PayrollMonth" ON "PayrollClosures" ("TenantId", "PayrollMonth");
                """,
                """
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "BaseSalary" numeric(18,2) NOT NULL DEFAULT 0;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "SalaryCoefficient" numeric(18,2) NOT NULL DEFAULT 1;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "StandardWorkDays" integer NOT NULL DEFAULT 26;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "StandardWorkHoursPerDay" numeric(18,2) NOT NULL DEFAULT 8;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "OvertimeHourlyMultiplier" numeric(18,2) NOT NULL DEFAULT 1.5;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LatePenaltyPerMinute" numeric(18,2) NOT NULL DEFAULT 2000;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FixedAllowance" numeric(18,2) NOT NULL DEFAULT 0;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "OtherIncome" numeric(18,2) NOT NULL DEFAULT 0;
                UPDATE "Users"
                SET "BaseSalary" = CASE
                    WHEN "DepartmentId" = 1 OR "JobTitleId" = 1 OR "PositionId" = 1 THEN 80000000
                    WHEN "DepartmentId" = 4 OR "PositionId" = 4 THEN 17000000
                    WHEN "DepartmentId" = 3 THEN 15000000
                    WHEN "JobTitleId" = 3 OR "PositionId" IN (2, 3, 5) THEN 25000000
                    ELSE 10000000
                END
                WHERE COALESCE("BaseSalary", 0) <= 0;
                """,
                """
                CREATE TABLE IF NOT EXISTS "PayrollSlips" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "PayrollClosureId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "PayrollMonth" character varying(20) NOT NULL,
                    "BaseSalary" numeric(18,2) NOT NULL DEFAULT 0,
                    "SalaryCoefficient" numeric(18,2) NOT NULL DEFAULT 1,
                    "StandardWorkDays" integer NOT NULL DEFAULT 26,
                    "StandardWorkHoursPerDay" numeric(18,2) NOT NULL DEFAULT 8,
                    "ActualWorkingDays" integer NOT NULL DEFAULT 0,
                    "ActualWorkHours" numeric(18,2) NOT NULL DEFAULT 0,
                    "OvertimeHours" numeric(18,2) NOT NULL DEFAULT 0,
                    "LateMinutes" integer NOT NULL DEFAULT 0,
                    "HourlyRate" numeric(18,2) NOT NULL DEFAULT 0,
                    "MainSalary" numeric(18,2) NOT NULL DEFAULT 0,
                    "OvertimeSalary" numeric(18,2) NOT NULL DEFAULT 0,
                    "FixedAllowance" numeric(18,2) NOT NULL DEFAULT 0,
                    "OtherIncome" numeric(18,2) NOT NULL DEFAULT 0,
                    "LatePenalty" numeric(18,2) NOT NULL DEFAULT 0,
                    "AdvanceDeduction" numeric(18,2) NOT NULL DEFAULT 0,
                    "NetSalary" numeric(18,2) NOT NULL DEFAULT 0,
                    "PdfPath" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_PayrollSlips_PayrollClosures_PayrollClosureId" FOREIGN KEY ("PayrollClosureId") REFERENCES "PayrollClosures" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_PayrollSlips_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PayrollSlips_PayrollClosureId_UserId" ON "PayrollSlips" ("PayrollClosureId", "UserId");
                """,
                """
                UPDATE "SlaConfigs"
                SET "ReminderHours" = 4,
                    "EscalationHours" = 8
                WHERE "FormTemplateId" = 1;

                UPDATE "SlaConfigs"
                SET "ReminderHours" = 24,
                    "EscalationHours" = 36
                WHERE "FormTemplateId" = 4;
                """,
                """
                CREATE TABLE IF NOT EXISTS "AttendanceAdjustmentRequests" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "SourceRequestId" integer NULL,
                    "UserId" integer NOT NULL,
                    "TimesheetId" integer NULL,
                    "AttendanceDate" timestamp without time zone NOT NULL,
                    "RequestedCheckIn" timestamp without time zone NULL,
                    "RequestedCheckOut" timestamp without time zone NULL,
                    "Reason" character varying(500) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "ApprovedByUserId" integer NULL,
                    "ProcessedAt" timestamp without time zone NULL,
                    "Notes" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_AttendanceAdjustmentRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AttendanceAdjustmentRequests_Timesheets_TimesheetId" FOREIGN KEY ("TimesheetId") REFERENCES "Timesheets" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AttendanceAdjustmentRequests_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_AttendanceAdjustmentRequests_UserId_AttendanceDate" ON "AttendanceAdjustmentRequests" ("UserId", "AttendanceDate");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_AttendanceAdjustmentRequests_SourceRequestId" ON "AttendanceAdjustmentRequests" ("SourceRequestId");
                """,
                """
                CREATE TABLE IF NOT EXISTS "LateEarlyRequests" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "SourceRequestId" integer NULL,
                    "UserId" integer NOT NULL,
                    "AttendanceDate" timestamp without time zone NOT NULL,
                    "RequestType" character varying(30) NOT NULL,
                    "ExpectedTime" timestamp without time zone NOT NULL,
                    "ActualTime" timestamp without time zone NOT NULL,
                    "Reason" character varying(500) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "ApprovedByUserId" integer NULL,
                    "ProcessedAt" timestamp without time zone NULL,
                    "Notes" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_LateEarlyRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_LateEarlyRequests_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_LateEarlyRequests_UserId_AttendanceDate" ON "LateEarlyRequests" ("UserId", "AttendanceDate");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_LateEarlyRequests_SourceRequestId" ON "LateEarlyRequests" ("SourceRequestId");
                """,
                """
                CREATE TABLE IF NOT EXISTS "ShiftImportBatches" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "FileName" character varying(255) NOT NULL,
                    "ImportedByUserId" integer NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "TotalRows" integer NOT NULL DEFAULT 0,
                    "SuccessRows" integer NOT NULL DEFAULT 0,
                    "FailedRows" integer NOT NULL DEFAULT 0,
                    "Summary" character varying(2000) NULL,
                    "ImportedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_ShiftImportBatches_Users_ImportedByUserId" FOREIGN KEY ("ImportedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "AutoShiftPlans" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "Name" character varying(150) NOT NULL,
                    "FromDate" timestamp without time zone NOT NULL,
                    "ToDate" timestamp without time zone NOT NULL,
                    "DepartmentId" integer NULL,
                    "Strategy" character varying(30) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "GeneratedByUserId" integer NOT NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_AutoShiftPlans_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AutoShiftPlans_Users_GeneratedByUserId" FOREIGN KEY ("GeneratedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "AutoShiftPlanItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "PlanId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "ShiftId" integer NOT NULL,
                    "WorkDate" timestamp without time zone NOT NULL,
                    "ConfidenceScore" double precision NOT NULL DEFAULT 0,
                    "Source" character varying(30) NOT NULL,
                    CONSTRAINT "FK_AutoShiftPlanItems_AutoShiftPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "AutoShiftPlans" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_AutoShiftPlanItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AutoShiftPlanItems_Shifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "Shifts" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_AutoShiftPlanItems_UserId_WorkDate" ON "AutoShiftPlanItems" ("UserId", "WorkDate");
                """,
                """
                CREATE TABLE IF NOT EXISTS "ShiftTaskAssignments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "ShiftId" integer NOT NULL,
                    "WorkDate" timestamp without time zone NOT NULL,
                    "AssignedToUserId" integer NOT NULL,
                    "AssignedByUserId" integer NOT NULL,
                    "Title" character varying(200) NOT NULL,
                    "Description" character varying(2000) NULL,
                    "Priority" character varying(20) NOT NULL,
                    "Status" character varying(20) NOT NULL,
                    "DueAt" timestamp without time zone NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_ShiftTaskAssignments_Shifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "Shifts" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_ShiftTaskAssignments_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_ShiftTaskAssignments_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "EmployeeOnlineSessions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "SessionToken" character varying(100) NOT NULL,
                    "LoginAt" timestamp without time zone NOT NULL,
                    "LastSeenAt" timestamp without time zone NOT NULL,
                    "LogoutAt" timestamp without time zone NULL,
                    "Status" character varying(20) NOT NULL,
                    "LastIpAddress" character varying(50) NULL,
                    "DeviceName" character varying(255) NULL,
                    CONSTRAINT "FK_EmployeeOnlineSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_EmployeeOnlineSessions_UserId_Status" ON "EmployeeOnlineSessions" ("UserId", "Status");
                """,
                """
                CREATE TABLE IF NOT EXISTS "DigitalSignatureProfiles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "ProviderName" character varying(100) NOT NULL,
                    "CertificateThumbprint" character varying(200) NULL,
                    "SignatureImageUrl" character varying(500) NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_DigitalSignatureProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "KpiSnapshots" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "UserId" integer NULL,
                    "DepartmentId" integer NULL,
                    "SnapshotDate" timestamp without time zone NOT NULL,
                    "MetricName" character varying(100) NOT NULL,
                    "MetricValue" double precision NOT NULL DEFAULT 0,
                    "Unit" character varying(20) NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_KpiSnapshots_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_KpiSnapshots_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS "RequestCategoryReportSnapshots" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "Category" character varying(100) NOT NULL,
                    "FromDate" timestamp without time zone NOT NULL,
                    "ToDate" timestamp without time zone NOT NULL,
                    "TotalRequests" integer NOT NULL DEFAULT 0,
                    "ApprovedRequests" integer NOT NULL DEFAULT 0,
                    "RejectedRequests" integer NOT NULL DEFAULT 0,
                    "PendingRequests" integer NOT NULL DEFAULT 0,
                    "AverageHoursToComplete" double precision NOT NULL DEFAULT 0,
                    "GeneratedByUserId" integer NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "FK_RequestCategoryReportSnapshots_Users_GeneratedByUserId" FOREIGN KEY ("GeneratedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                """
            };

            foreach (var command in commands)
            {
                await db.Database.ExecuteSqlRawAsync(command);
            }

            var alterCommands = new[]
            {
                """
                ALTER TABLE "PasswordHistories" ADD COLUMN IF NOT EXISTS "TenantId" integer NOT NULL DEFAULT 1;
                ALTER TABLE "PasswordHistories" ADD COLUMN IF NOT EXISTS "ChangeSource" character varying(50) NOT NULL DEFAULT 'SelfService';
                """,
                """
                ALTER TABLE "DigitalSignatureProfiles" ADD COLUMN IF NOT EXISTS "SignatureName" character varying(150) NOT NULL DEFAULT 'Chữ ký mặc định';
                """,
                """
                ALTER TABLE "KpiSnapshots" ADD COLUMN IF NOT EXISTS "MetricCode" character varying(50) NOT NULL DEFAULT 'GENERAL';
                ALTER TABLE "KpiSnapshots" ADD COLUMN IF NOT EXISTS "Category" character varying(50) NOT NULL DEFAULT 'General';
                """,
                """
                ALTER TABLE "RequestCategoryReportSnapshots" ADD COLUMN IF NOT EXISTS "SnapshotDate" timestamp without time zone NOT NULL DEFAULT NOW();
                """,
                """
                ALTER TABLE "AuthAuditLogs" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp without time zone NOT NULL DEFAULT NOW();
                """,
                """
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "RegisteredMacAddress" character varying(32) NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "RegisteredLoginIp" character varying(64) NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "RememberMeTokenHash" character varying(128) NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "RememberMeExpiresAt" timestamp without time zone NULL;
                UPDATE "Users"
                SET "EmployeeCode" = CASE
                    WHEN "Email" = 'admin@company.com' THEN 'AD001'
                    WHEN "Email" = 'hr@company.com' THEN 'HR001'
                    WHEN "Email" = 'manager@company.com' THEN 'MNG001'
                    WHEN "Email" = 'employee@company.com' THEN 'NV001'
                    WHEN "Email" = 'accountant@company.com' THEN 'KT001'
                    WHEN "Email" = 'dev@company.com' THEN 'NV002'
                    WHEN "Email" = 'sales@company.com' THEN 'NV003'
                    WHEN "Email" = 'marketing@company.com' THEN 'NV004'
                    ELSE "EmployeeCode"
                END;
                """
            };

            foreach (var command in alterCommands)
            {
                await db.Database.ExecuteSqlRawAsync(command);
            }
        }
    }
}
